name: Random code snippet

on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Fowdre
          template: classic
          base: ""
          config_timezone: Europe/Paris
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_languages: c, python, c++, haskell
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: all
