name: Metrics

on:
  schedule:
    # runs at 23:00 Paris time
    - cron: "0 21 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Code Snippet of the Day
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/code_snippet.svg
          base: ""
          plugin_code: yes
          plugin_code_lines: 12
          plugin_code_visibility: public
          plugin_code_days: 1
