name: Metrics

on:
  schedule: [{cron: "0 */8 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Code Snippet of the Day
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/code_snippet.svg
          base: ""
          plugin_code: yes
          plugin_code_lines: 12
          plugin_code_visibility: public
